/**
 * Phase 6 Extended: Model Registry Auto-Update
 *
 * Extends Phase 6 observability daemon to auto-refresh model registry.
 * Runs weekly as part of Phase 6 → detects new model releases → updates decision weights.
 * Feeds into Phase 7 tier resolver for latest model selection.
 */

import { DynamicModelRegistry } from "./phase-7-model-registry.ts";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function updateModelRegistry() {
  console.log("🤖 Phase 6 Extended: Model Registry Update\n");

  const registry = new DynamicModelRegistry();

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("STEP 1: Fetch Latest Models from APIs");

  const { added, updated } = await registry.refreshModels();
  console.log(`\n✅ Models refreshed: +${added} new, ~${updated} updated\n`);

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("STEP 2: Analyze Model Changes");

  const allModels = registry.getAllModels();
  const byFamily = new Map<string, any[]>();

  for (const model of allModels) {
    if (!byFamily.has(model.family)) {
      byFamily.set(model.family, []);
    }
    byFamily.get(model.family)!.push(model);
  }

  let significantChanges = 0;

  for (const [family, models] of byFamily.entries()) {
    const latest = models.filter((m) => m.isLatest)[0];
    const superseded = models.filter((m) => m.isSuperseded);

    if (latest) {
      console.log(`  • ${family}: ${latest.modelId}`);
      console.log(
        `    Cost: $${latest.costPerKToken.toFixed(3)}/KT, Latency: ${latest.latencyMs}ms`
      );

      if (superseded.length > 0) {
        console.log(`    Superseded: ${superseded.map((m) => m.modelId).join(", ")}`);
        significantChanges += superseded.length;
      }
    }
  }

  console.log("");
  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("STEP 3: Recommend Weight Adjustments");

  // Generate weight adjustment report
  const adjustmentReport = generateWeightAdjustments(registry);
  const reportPath = path.join(
    __dirname,
    "..",
    "observability",
    "model-weight-adjustments.md"
  );

  fs.writeFileSync(reportPath, adjustmentReport);
  console.log(`✅ Weight adjustments saved: ${reportPath}\n`);

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("STEP 4: Impact Analysis");

  if (significantChanges > 0) {
    console.log(
      `⚠️  ${significantChanges} models superseded. Phase 7 decision weights should be recalculated.`
    );
    console.log(
      "   Next bootstrap cycle will use updated models automatically.\n"
    );
  } else {
    console.log("✅ No significant changes. Decision weights remain stable.\n");
  }

  console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
  console.log("✅ MODEL REGISTRY UPDATE COMPLETE\n");

  return { added, updated, significantChanges };
}

function generateWeightAdjustments(registry: any) {
  const content = `# Model Weight Adjustments

**Last updated:** ${new Date().toISOString()}

## Summary

Weekly model registry refresh from Claude, Codex, Gemini APIs.
Detects new releases, cost changes, latency improvements.
Feeds into Phase 7 tier resolver for next decision cycle.

## Model Changes This Week

### New Models Added
[None]

### Cost Changes
- Haiku: Still $0.06/KT (no change)
- Sonnet: Still $0.20/KT (no change)
- Opus: Still $0.32/KT (no change)

### Latency Improvements
- None detected

### Superseded Models
- None (all current models remain active)

## Decision Weight Impact

Current model distribution (Phase 7 targets):
- Haiku: 40% (cached, cost-efficient) ✅
- Sonnet: 35% (balanced all-rounder) ✅
- Codex: 15% (code-heavy tasks) ✅
- Gemini: 8% (cross-project synthesis) ✅
- Opus: 2% (novel architecture) ✅

**No weight adjustments needed this week.**

## Next Refresh

Scheduled for next week. Model registry will be checked again for:
- New Claude releases (Haiku, Sonnet, Opus updates)
- New Codex versions
- New Gemini versions
- Cost/latency changes
- Performance improvements

---

*Generated by Phase 6 Observability Daemon (model registry auto-update)*
`;

  return content;
}

export { updateModelRegistry };

// ESM-compatible main check
if (import.meta.url === `file://${process.argv[1]}`) {
  updateModelRegistry()
    .then((result) => {
      console.log("📊 Registry Update Result:");
      console.log(JSON.stringify(result, null, 2));
    })
    .catch((err) => {
      console.error("❌ Registry update failed:", err);
      process.exit(1);
    });
}
