#!/usr/bin/env bash
# ark report — generate stakeholder reports
#
# Usage:
#   ark report --for customer    # customer-facing project update
#   ark report --for investor    # investor update with metrics
#   ark report --for team        # internal team status
#   ark report --for self        # raw CEO-level report

set -uo pipefail

PROJECT_DIR="$(pwd)"
AUDIENCE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --for) AUDIENCE="$2"; shift 2 ;;
    *) shift ;;
  esac
done

[[ -z "$AUDIENCE" ]] && AUDIENCE="self"

PROJECT_NAME=$(basename "$PROJECT_DIR")
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
REPORT_DIR="$PROJECT_DIR/.planning/reports"
mkdir -p "$REPORT_DIR"
REPORT_FILE="$REPORT_DIR/${AUDIENCE}-$(date +%Y-%m-%d).md"

# Gather data
PHASES_COMPLETED=$(ls "$PROJECT_DIR/.planning/phase-"*-ceo-report.md 2>/dev/null | xargs grep -l "DELIVERED" 2>/dev/null | wc -l | tr -d ' ' || echo 0)
PHASES_TOTAL=$(grep -cE "^## Phase [0-9]+" "$PROJECT_DIR/.planning/ROADMAP.md" 2>/dev/null || echo 0)
DECISIONS=$(wc -l < "$PROJECT_DIR/.planning/bootstrap-decisions.jsonl" 2>/dev/null | tr -d ' ' || echo 0)
LAST_DELIVERY=$(ls -t "$PROJECT_DIR/.planning/phase-"*-ceo-report.md 2>/dev/null | head -1)
LAST_DELIVERY_DATE=""
[[ -n "$LAST_DELIVERY" ]] && LAST_DELIVERY_DATE=$(grep "^\*\*Date:" "$LAST_DELIVERY" 2>/dev/null | head -1 | sed 's/.*Date:\*\*[[:space:]]*//' || echo "")

CURRENT_PHASE=$(grep -oE "Phase [0-9]+" "$PROJECT_DIR/.planning/STATE.md" 2>/dev/null | head -1 || echo "Phase 0")

# Tokens used
TOKENS_USED=0
if [[ -f "$PROJECT_DIR/.planning/budget.json" ]]; then
  TOKENS_USED=$(python3 -c "
import json
with open('$PROJECT_DIR/.planning/budget.json') as f:
    print(json.load(f).get('monthly_used', 0))
" 2>/dev/null || echo 0)
fi

case "$AUDIENCE" in
  customer)
    cat > "$REPORT_FILE" <<EOF
# $PROJECT_NAME — Customer Update

**Date:** $(date +"%B %d, %Y")

## Project Status

We're currently working on **$CURRENT_PHASE** of the $PROJECT_NAME project.

## Recent Progress

$([ "$PHASES_COMPLETED" -gt 0 ] && echo "We've completed $PHASES_COMPLETED of $PHASES_TOTAL planned phases." || echo "We're in the early stages of development.")

$([ -n "$LAST_DELIVERY_DATE" ] && echo "Last delivery: $LAST_DELIVERY_DATE")

## What's Coming Next

$(grep -A3 "^## $CURRENT_PHASE" "$PROJECT_DIR/.planning/ROADMAP.md" 2>/dev/null | tail -3 || echo "Continuing implementation per the agreed roadmap.")

## Quality Assurance

Every change passes through:
- ✓ Architecture review
- ✓ Code quality review
- ✓ Functional testing
- ✓ Security audit
- ✓ Project manager sign-off

We'll send the next update when the current phase is delivered.

---
For technical questions, contact your account manager.
EOF
    ;;

  investor)
    cat > "$REPORT_FILE" <<EOF
# $PROJECT_NAME — Investor Update

**Reporting Period:** $(date +"%B %Y")

## Executive Summary

$PROJECT_NAME has completed $PHASES_COMPLETED of $PHASES_TOTAL roadmap phases.

## Key Metrics

| Metric | Value |
|--------|-------|
| Project Status | $CURRENT_PHASE |
| Phases Delivered | $PHASES_COMPLETED / $PHASES_TOTAL |
| Decisions Made | $DECISIONS |
| Token Spend (this month) | $(printf "%'d" $TOKENS_USED) |
| Last Delivery | ${LAST_DELIVERY_DATE:-N/A} |

## Risks & Blockers

$(ls "$PROJECT_DIR/.planning/phase-"*-ceo-report.md 2>/dev/null | xargs grep -l "BLOCKED" 2>/dev/null | wc -l | xargs -I{} echo "{} blocked phase(s)")

## Roadmap Velocity

Average delivery cadence: based on autonomous AI delivery pipeline with multi-role validation gates.

## Next Milestones

$(grep -B1 "^## Phase" "$PROJECT_DIR/.planning/ROADMAP.md" 2>/dev/null | grep -E "^- \[ \]" | head -3)

---
*Generated by Ark Portfolio Management*
EOF
    ;;

  team)
    cat > "$REPORT_FILE" <<EOF
# $PROJECT_NAME — Team Status

**Date:** $TIMESTAMP

## Current Sprint

$CURRENT_PHASE — see .planning/phase-${CURRENT_PHASE//Phase /}/PLAN.md

## Recent Phase Reports

$(ls -t "$PROJECT_DIR/.planning/phase-"*-ceo-report.md 2>/dev/null | head -3 | while read f; do
  echo "### $(basename "$f")"
  head -10 "$f"
  echo ""
done)

## Active TODOs

$(head -20 "$PROJECT_DIR/tasks/todo.md" 2>/dev/null || echo "No todos")

## Recent Lessons

$(tail -20 "$PROJECT_DIR/tasks/lessons.md" 2>/dev/null || echo "None")

## Ark State

- Decisions logged: $DECISIONS
- Tokens used (month): $TOKENS_USED
- Snapshot: \`ark status\` for details
EOF
    ;;

  self|*)
    cat > "$REPORT_FILE" <<EOF
# $PROJECT_NAME — CEO Report

**Date:** $TIMESTAMP

## Position
- Phase: $CURRENT_PHASE
- Phases delivered: $PHASES_COMPLETED / $PHASES_TOTAL
- Decisions: $DECISIONS

## Token Spend
$(bash "$VAULT_PATH/scripts/ark-budget.sh" 2>/dev/null || echo "Budget tracking unavailable")

## Recent Phases
$(ls -t "$PROJECT_DIR/.planning/phase-"*-ceo-report.md 2>/dev/null | head -3 | while read f; do
  status=$(grep -oE "(DELIVERED|BLOCKED)" "$f" | head -1)
  date=$(grep "^\*\*Date:" "$f" | sed 's/.*Date:\*\*[[:space:]]*//')
  echo "  - $(basename "$f"): $status ($date)"
done)

## Next Action
$(grep "^Run \`brain" "$LAST_DELIVERY" 2>/dev/null | head -1 || echo "Run: ark status")
EOF
    ;;
esac

echo "✅ Report saved: $REPORT_FILE"
echo ""
echo "Preview:"
head -25 "$REPORT_FILE"
